# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/sd-playground',
                'doc_host': 'https://pablo-unzueta.github.io',
                'git_url': 'https://github.com/pablo-unzueta/sd-playground',
                'lib_path': 'sd_playground'},
  'syms': { 'sd_playground.AtomsToGraph': { 'sd_playground.AtomsToGraph.generate_onehot_features': ( 'atomstograph.html#generate_onehot_features',
                                                                                                     'sd_playground/AtomsToGraph.py')},
            'sd_playground.basis': { 'sd_playground.basis.GaussianRandomFourierFeatures': ( 'basis.html#gaussianrandomfourierfeatures',
                                                                                            'sd_playground/basis.py'),
                                     'sd_playground.basis.GaussianSmearing': ('basis.html#gaussiansmearing', 'sd_playground/basis.py'),
                                     'sd_playground.basis.GaussianSmearing.__init__': ( 'basis.html#gaussiansmearing.__init__',
                                                                                        'sd_playground/basis.py'),
                                     'sd_playground.basis.GaussianSmearing.forward': ( 'basis.html#gaussiansmearing.forward',
                                                                                       'sd_playground/basis.py'),
                                     'sd_playground.basis.bessel_features': ('basis.html#bessel_features', 'sd_playground/basis.py')},
            'sd_playground.core': {'sd_playground.core.foo': ('core.html#foo', 'sd_playground/core.py')}}}
