# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_AtomsToGraph.ipynb.

# %% auto 0
__all__ = ['generate_onehot_features']

# %% ../nbs/00_AtomsToGraph.ipynb 3
from ase.io import read, write
from ase import Atoms
from sklearn.preprocessing import OneHotEncoder
import numpy as np

# %% ../nbs/00_AtomsToGraph.ipynb 6
def generate_onehot_features(symbols):
    """Generate one-hot features for a list of atom symbols.

    Args:
        symbols (list): List of atom symbols.

    Returns:
        numpy.ndarray: One-hot features.
    """
    symbols = np.array(symbols).reshape(-1, 1) # Convert List to 2D array with N rows and 1 column
    enc = OneHotEncoder(sparse_output=False)
    enc.fit(symbols) # Creates one-hot encoder with N rows and M unique elments for the columns
    return enc.transform(symbols)
