name: CI
on:  [workflow_dispatch, pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps: 
      - uses: pablo-unzueta/workflows/nbdev-ci-sd@master
        with: 
          version: "3.10"

